Repository cargillj/OldMan, pull requests merged in 2019-11, with the labels that each got.

#7 Old person picture command
  package-lock.json
  package.json
  src/ResponseManager/ResponseManager.ts
  src/responses/commands.ts
  src/tests/responses/commands.test.ts
Labels: bug, enhancement, good first issue

#14 feat: #11 Add probability to Response
  src/ResponseManager/Response.ts
  src/responses/bullyisms.ts
  src/responses/commands.ts
  src/tests/ResponseManager/ResponseManager.test.ts
  src/tests/responses/bullyisms.test.ts
Labels: enhancement

#13 Refactor/winston singleton
  .gitignore
  jest.config.js
  package-lock.json
  package.json
  src/tests/setup.ts
  src/utils/Logger.ts
Labels: tech debt

#19 Feat/life events
  CHANGELOG.md
  package-lock.json
  package.json
  src/DiscordBot/DiscordBot.ts
  src/DiscordBot/Managers/EventManager/BotEvents.ts
  src/DiscordBot/Managers/EventManager/EventManager.ts
  src/DiscordBot/Managers/EventManager/ScheduledEvents.ts
  src/DiscordBot/Managers/EventManager/index.ts
  src/DiscordBot/Managers/ResponseManager/Response.ts
  src/DiscordBot/Managers/ResponseManager/ResponseManager.ts
  src/DiscordBot/Managers/ResponseManager/index.ts
  src/DiscordBot/Managers/StatManager/Stat.ts
  src/DiscordBot/Managers/StatManager/StatManager.ts
  src/DiscordBot/Managers/StatManager/index.ts
  src/DiscordBot/Managers/index.ts
  src/DiscordBot/index.ts
  src/OldManBot/OldMan.ts
  src/OldManBot/events/constants.ts
  src/OldManBot/events/index.ts
  src/OldManBot/events/lifecycleEvents.ts
  src/OldManBot/events/scheduledEvents.ts
  src/OldManBot/metadata.ts
  src/OldManBot/responses/bullyisms.ts
  src/OldManBot/responses/commands.ts
  src/OldManBot/responses/index.ts
  src/OldManBot/responses/offensives.ts
  src/OldManBot/scenarios/hospitalized/constants.ts
  src/OldManBot/scenarios/hospitalized/events/discharged.ts
  src/OldManBot/scenarios/hospitalized/events/hospitalized.ts
  src/OldManBot/scenarios/hospitalized/events/index.ts
  src/OldManBot/scenarios/hospitalized/index.ts
  src/OldManBot/scenarios/hospitalized/responses/commands.ts
  src/OldManBot/scenarios/hospitalized/responses/index.ts
  src/OldManBot/scenarios/index.ts
  src/OldManBot/stats/health.ts
  src/OldManBot/stats/hunger.ts
  src/OldManBot/stats/index.ts
  src/bot.ts
  src/tests/DiscordBot/Managers/EventManager/EventManager.test.ts
  src/tests/DiscordBot/Managers/ResponseManager/ResponseManager.test.ts
  src/tests/DiscordBot/Managers/StatManager/StatManager.test.ts
  src/tests/OldManBot/responses/bullyisms.test.ts
  src/tests/OldManBot/responses/commands.test.ts
  src/tests/OldManBot/responses/offensives.test.ts
  src/tests/responses/offensives.test.ts
  src/utils/Bot.ts
  src/utils/Logger.ts
  src/utils/textStyler.ts
Labels: enhancement

#28 refactor: update DiscordBot API
  jest.config.js
  src/DiscordBot/DiscordBot.ts
  src/DiscordBot/index.ts
  src/DiscordBot/tests/Managers/EventManager/EventManager.test.ts
  src/DiscordBot/tests/Managers/ResponseManager/ResponseManager.test.ts
  src/DiscordBot/tests/Managers/StatManager/StatManager.test.ts
  src/DiscordBot/tests/setup.ts
  src/DiscordBot/utils/Logger.ts
  src/OldManBot/OldMan.ts
  src/OldManBot/events/lifecycleEvents.ts
  src/OldManBot/events/scheduledEvents.ts
  src/OldManBot/responses/bullyisms.ts
  src/OldManBot/responses/commands.ts
  src/OldManBot/responses/offensives.ts
  src/OldManBot/scenarios/hospitalized/events/discharged.ts
  src/OldManBot/scenarios/hospitalized/events/hospitalized.ts
  src/OldManBot/scenarios/hospitalized/responses/commands.ts
  src/OldManBot/stats/health.ts
  src/OldManBot/stats/hunger.ts
  src/OldManBot/tests/responses/bullyisms.test.ts
  src/OldManBot/tests/responses/commands.test.ts
  src/OldManBot/tests/responses/offensives.test.ts
  src/OldManBot/utils/textStyler.ts
  tsconfig.json
Labels: tech debt
